spark.conf.set("mapreduce.input.fileinputformat.input.dir.recursive", "true")
spark.conf.set("spark.sql.hive.convertMetastoreParquet", "false")

spark.sql("""INSERT OVERWRITE TABLE  advance_services_bkp_db.CHILDSKU_EXECUTIVE_DASHBOARD_FNL 
SELECT
BKGS.DV_SOURCE_ORDER_NUM_INT
,BKGS.BK_AS_QUOTE_NUM
,BKGS.QUOTE_TYPE
,BKGS.BK_DELIVERABLE_NAME
,BKGS.BK_ALLOCATED_SERVC_GROUP_ID AS SERVICE_TYPE
,BKGS.BK_AS_ARCHITECTURE_NAME AS ARCHITECTURE
,BKGS.BK_AS_TECHNOLOGY_NAME AS TECHNOLOGY
,BKGS.BK_AS_BUSINESS_SERVICE_NAME AS BUSINESS_SERVICE
,BKGS.BK_SUB_BUSINESS_ENTITY_NAME
,BKGS.PART_ID
,BKGS.FISCAL_QUARTER_NAME AS FISCAL_QUARTER
,BKGS.FISCAL_QTR_AGE
,BKGS.SALES_TERRITORY_KEY
,BKGS.DRR_NORMALIZED_CUSTOMER_NAME
,BKGS.ATTRIBUTION_METHODOLOGY_CD
,SUM(DV_TOTAL_BOOKING_AMT) AS TOTAL_BOOKINGS
,SUM(DV_MULTIYEAR_US_NET_AMT) AS MY_BOOKINGS
,SUM(DV_ANNUAL_US_NET_AMT) AS ANNUAL_BOOKINGS
,SUM(DV_ANNUALIZED_US_NET_AMT) AS ANNUALIZED_BOOKINGS
,SUM(DV_ANNUITY_AMT) AS ANNUITY_BOOKINGS
,BKGS.BK_AS_ATO_ARCHI_NAME AS ATO_ARCH_NAME
,BKGS.DV_AS_ATO_TECH_NAME AS ATO_TECH_NAME
,BKGS.BK_BUSI_SVC_OFFER_TYPE_NAME AS ATO_OFFER_TYPE
,BKGS.BK_DEAL_ID
,BKGS.deliverable_description
,BKGS.OFFER_NAME
,BKGS.OFFER_ABBREVATION
,BKGS.erp_wips_customer_name
,END_CUST.GU_PRIMARY_NAME   END_CUST_GU_NAME           
,PV_SALES_HIERARCHY.L1_SALES_TERRITORY_DESCR AS  NODE_LEVEL_1_CODE
,PV_SALES_HIERARCHY.L2_SALES_TERRITORY_DESCR AS  NODE_LEVEL_2_CODE
,PV_SALES_HIERARCHY.L3_SALES_TERRITORY_DESCR AS  NODE_LEVEL_3_CODE
,PV_SALES_HIERARCHY.L4_SALES_TERRITORY_DESCR AS  NODE_LEVEL_4_CODE
,PV_SALES_HIERARCHY.L5_SALES_TERRITORY_DESCR AS  NODE_LEVEL_5_CODE
,PV_SALES_HIERARCHY.L6_SALES_TERRITORY_DESCR AS  NODE_LEVEL_6_CODE
,PV_SALES_HIERARCHY.SALES_COVERAGE_CODE AS SCMS
FROM 
(SELECT * FROM advance_services_db.PV_MT_AS_QUOTE_SKU_BKGS     
WHERE FISCAL_QTR_AGE between 0 and 5) BKGS 
INNER JOIN reference_tdprod_datalakepvwdb.PV_SALES_HIERARCHY PV_SALES_HIERARCHY
            ON      BKGS.SALES_TERRITORY_KEY = PV_SALES_HIERARCHY.SALES_TERRITORY_KEY
LEFT JOIN reference_tdprod_datalakepvwdb.PV_ENDCUST_CUST_PARTY_HIER END_CUST
ON BKGS.end_customer_key = END_CUST.end_customer_key
GROUP BY 
BKGS.DV_SOURCE_ORDER_NUM_INT
,BKGS.BK_AS_QUOTE_NUM
,BKGS.QUOTE_TYPE
,BKGS.BK_DELIVERABLE_NAME
,BKGS.BK_ALLOCATED_SERVC_GROUP_ID
,BKGS.BK_AS_ARCHITECTURE_NAME
,BKGS.BK_AS_TECHNOLOGY_NAME
,BKGS.BK_AS_BUSINESS_SERVICE_NAME
,BKGS.BK_SUB_BUSINESS_ENTITY_NAME
,BKGS.PART_ID
,BKGS.FISCAL_QUARTER_NAME
,BKGS.FISCAL_QTR_AGE
,BKGS.SALES_TERRITORY_KEY
,BKGS.DRR_NORMALIZED_CUSTOMER_NAME
,BKGS.ATTRIBUTION_METHODOLOGY_CD
,BKGS.BK_AS_ATO_ARCHI_NAME
,BKGS.DV_AS_ATO_TECH_NAME
,BKGS.BK_BUSI_SVC_OFFER_TYPE_NAME
,BKGS.BK_DEAL_ID
,BKGS.deliverable_description
,BKGS.OFFER_NAME
,BKGS.OFFER_ABBREVATION
,PV_SALES_HIERARCHY.L1_SALES_TERRITORY_DESCR
,PV_SALES_HIERARCHY.L2_SALES_TERRITORY_DESCR
,PV_SALES_HIERARCHY.L3_SALES_TERRITORY_DESCR
,PV_SALES_HIERARCHY.L4_SALES_TERRITORY_DESCR
,PV_SALES_HIERARCHY.L5_SALES_TERRITORY_DESCR
,PV_SALES_HIERARCHY.L6_SALES_TERRITORY_DESCR
,PV_SALES_HIERARCHY.DD_EXTERNAL_THEATER_NAME
,PV_SALES_HIERARCHY.SALES_COVERAGE_CODE
,END_CUST.GU_PRIMARY_NAME
,bkgs.erp_wips_customer_name""")

System.exit(0)
